### ISSUE TITLE
Needs Review

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-capistrano#2]
Upon further review I'm not sure we can include this as an official plugin. Official plugins have a strict policy that they do not execute arbitrary code, as a security measure. It looks like (and feel free to correct me) that capistrano runs arbitrary ruby code from the repository.

Perhaps running capistrano using the new multi-build section, with conditional logic, makes more sense?
http://readme.drone.io/usage/build_test/#multiple-steps:fb92aa3346185c57f15afda861d465a3

You could do something like this:

```yaml
build:
  test:
    image: ruby
    commands:
      - bundle install
      - bundle exec rake:test
  cap:
    image: ruby
    commands:
      - bundle exec cap
    when:
      event: push  # prevents execution during pull requests!
      branch: master
```

Or alternatively you can continue to use this as an unofficial plugin.

Sorry I would have brought this up earlier but I have very little knowledge of Capistrano and didn't realize this until reviewing the code and googling Capistrano.
